"""add complemento nomina

Revision ID: 0d4b9657c3a5
Revises: 64d3d0de94e2
Create Date: 2026-08-05 18:28:56.578006

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d4b9657c3a5'
down_revision: Union[str, Sequence[str], None] = '64d3d0de94e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nomina',
    sa.Column('comprobante_id', sa.Integer(), nullable=False),
    sa.Column('version_nomina', sa.String(length=5), nullable=True),
    sa.Column('tipo_nomina', sa.CHAR(length=1), nullable=True),
    sa.Column('fecha_pago', sa.Date(), nullable=True),
    sa.Column('fecha_inicial_pago', sa.Date(), nullable=True),
    sa.Column('fecha_final_pago', sa.Date(), nullable=True),
    sa.Column('num_dias_pagados', sa.Numeric(precision=9, scale=3), nullable=True),
    sa.Column('total_percepciones', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('total_deducciones', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('total_otros_pagos', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('registro_patronal', sa.String(length=20), nullable=True),
    sa.Column('rfc_patron_origen', sa.String(length=13), nullable=True),
    sa.Column('origen_recurso', sa.String(length=2), nullable=True),
    sa.Column('monto_recurso_propio', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.ForeignKeyConstraint(['comprobante_id'], ['comprobantes.comprobante_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('comprobante_id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci'
    )
    op.create_index('idx_nomina_fecha_pago', 'nomina', ['fecha_pago'], unique=False)
    op.create_index('idx_nomina_final_pago', 'nomina', ['fecha_final_pago'], unique=False)
    op.create_table('nomina_deduccion',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('comprobante_id', sa.Integer(), nullable=False),
    sa.Column('tipo_deduccion', sa.CHAR(length=3), nullable=False),
    sa.Column('clave', sa.String(length=15), nullable=True),
    sa.Column('concepto', sa.String(length=100), nullable=True),
    sa.Column('importe', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.ForeignKeyConstraint(['comprobante_id'], ['comprobantes.comprobante_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci'
    )
    op.create_index('idx_deduccion_concepto', 'nomina_deduccion', ['comprobante_id', 'tipo_deduccion', 'clave'], unique=False)
    op.create_table('nomina_incapacidad',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('comprobante_id', sa.Integer(), nullable=False),
    sa.Column('dias_incapacidad', sa.Integer(), nullable=True),
    sa.Column('tipo_incapacidad', sa.String(length=2), nullable=True),
    sa.Column('importe_monetario', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.ForeignKeyConstraint(['comprobante_id'], ['comprobantes.comprobante_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci'
    )
    op.create_index('idx_incapacidad_comp', 'nomina_incapacidad', ['comprobante_id'], unique=False)
    op.create_table('nomina_otro_pago',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('comprobante_id', sa.Integer(), nullable=False),
    sa.Column('tipo_otro_pago', sa.CHAR(length=3), nullable=False),
    sa.Column('clave', sa.String(length=15), nullable=True),
    sa.Column('concepto', sa.String(length=100), nullable=True),
    sa.Column('importe', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('subsidio_causado', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('saldo_a_favor', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('anio', sa.Integer(), nullable=True),
    sa.Column('remanente_sal_fav', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.ForeignKeyConstraint(['comprobante_id'], ['comprobantes.comprobante_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci'
    )
    op.create_index('idx_otro_pago_concepto', 'nomina_otro_pago', ['comprobante_id', 'tipo_otro_pago', 'clave'], unique=False)
    op.create_table('nomina_percepcion',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('comprobante_id', sa.Integer(), nullable=False),
    sa.Column('tipo_percepcion', sa.CHAR(length=3), nullable=False),
    sa.Column('clave', sa.String(length=15), nullable=True),
    sa.Column('concepto', sa.String(length=100), nullable=True),
    sa.Column('importe_gravado', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('importe_exento', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.ForeignKeyConstraint(['comprobante_id'], ['comprobantes.comprobante_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci'
    )
    op.create_index('idx_percepcion_concepto', 'nomina_percepcion', ['comprobante_id', 'tipo_percepcion', 'clave'], unique=False)
    op.create_table('nomina_receptor',
    sa.Column('comprobante_id', sa.Integer(), nullable=False),
    sa.Column('curp', sa.CHAR(length=18), nullable=True),
    sa.Column('nss', sa.String(length=15), nullable=True),
    sa.Column('fecha_inicio_rel_laboral', sa.Date(), nullable=True),
    sa.Column('antiguedad', sa.String(length=10), nullable=True),
    sa.Column('tipo_contrato', sa.String(length=2), nullable=True),
    sa.Column('sindicalizado', sa.String(length=2), nullable=True),
    sa.Column('tipo_jornada', sa.String(length=2), nullable=True),
    sa.Column('tipo_regimen', sa.String(length=2), nullable=True),
    sa.Column('num_empleado', sa.String(length=15), nullable=True),
    sa.Column('departamento', sa.String(length=100), nullable=True),
    sa.Column('puesto', sa.String(length=100), nullable=True),
    sa.Column('riesgo_puesto', sa.CHAR(length=1), nullable=True),
    sa.Column('periodicidad_pago', sa.String(length=2), nullable=True),
    sa.Column('banco', sa.String(length=3), nullable=True),
    sa.Column('cuenta_bancaria', sa.String(length=18), nullable=True),
    sa.Column('salario_base_cot_apor', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('salario_diario_integrado', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('clave_ent_fed', sa.String(length=3), nullable=True),
    sa.ForeignKeyConstraint(['comprobante_id'], ['comprobantes.comprobante_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('comprobante_id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci'
    )
    op.create_index('idx_nom_receptor_curp', 'nomina_receptor', ['curp'], unique=False)
    op.create_index('idx_nom_receptor_nss', 'nomina_receptor', ['nss'], unique=False)
    op.create_table('nomina_totales',
    sa.Column('comprobante_id', sa.Integer(), nullable=False),
    sa.Column('total_sueldos', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('total_separacion_indemnizacion', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('total_jubilacion_pension_retiro', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('total_gravado', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('total_exento', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('total_otras_deducciones', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('total_impuestos_retenidos', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.ForeignKeyConstraint(['comprobante_id'], ['comprobantes.comprobante_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('comprobante_id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # `idx_percepcion_concepto`, `idx_deduccion_concepto`, `idx_otro_pago_concepto` e
    # `idx_incapacidad_comp` empiezan con la columna de una FK hacia `comprobantes`:
    # InnoDB los usa para satisfacer esa FK, así que un `DROP INDEX` explícito falla con
    # el error 1553. Se dejan fuera y el propio `DROP TABLE` se lleva el índice (mismo
    # ajuste que en las migraciones de las tareas 1 y 2).
    op.drop_table('nomina_totales')
    op.drop_index('idx_nom_receptor_nss', table_name='nomina_receptor')
    op.drop_index('idx_nom_receptor_curp', table_name='nomina_receptor')
    op.drop_table('nomina_receptor')
    op.drop_table('nomina_percepcion')
    op.drop_table('nomina_otro_pago')
    op.drop_table('nomina_incapacidad')
    op.drop_table('nomina_deduccion')
    op.drop_index('idx_nomina_final_pago', table_name='nomina')
    op.drop_index('idx_nomina_fecha_pago', table_name='nomina')
    op.drop_table('nomina')
    # ### end Alembic commands ###
