"""add configuracion fiscal

Revision ID: 241164acbc81
Revises: 0d4b9657c3a5
Create Date: 2026-08-06 21:21:59.229488

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '241164acbc81'
down_revision: Union[str, Sequence[str], None] = '0d4b9657c3a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('catalogo_percepcion_marca',
    sa.Column('tipo_percepcion', sa.CHAR(length=3), nullable=False),
    sa.Column('es_ingreso_ordinario', sa.Boolean(), nullable=False),
    sa.Column('base_exencion', sa.Enum('UMA_DIAS', 'SM_DIAS', 'PORCENTAJE', 'NINGUNA', name='baseexencion'), nullable=False),
    sa.Column('factor_exencion', sa.Numeric(precision=9, scale=4), nullable=True),
    sa.Column('integra_sbc', sa.Boolean(), nullable=False),
    sa.Column('es_provisionable', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('tipo_percepcion'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci'
    )
    op.create_table('param_fiscal',
    sa.Column('clave', sa.String(length=40), nullable=False),
    sa.Column('vigencia_desde', sa.Date(), nullable=False),
    sa.Column('ejercicio', sa.Integer(), nullable=False),
    sa.Column('valor', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('vigencia_hasta', sa.Date(), nullable=True),
    sa.Column('origen', sa.Enum('SEMILLA', 'MANUAL', 'SINCRONIZADO', name='origenvalor'), nullable=False),
    sa.Column('fuente', sa.String(length=500), nullable=False),
    sa.Column('sincronizado_en', sa.DateTime(), nullable=True),
    sa.Column('confirmado_por', sa.String(length=128), nullable=True),
    sa.Column('confirmado_en', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('clave', 'vigencia_desde'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci'
    )
    op.create_table('tabla_vacaciones',
    sa.Column('anios_antiguedad', sa.Integer(), nullable=False),
    sa.Column('dias', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('anios_antiguedad'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci'
    )
    op.create_table('configuracion_empresa',
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('zona_salarial', sa.Enum('GENERAL', 'ZLFN', name='zonasalarial'), nullable=True),
    sa.Column('dias_aguinaldo', sa.Integer(), nullable=True),
    sa.Column('factor_prima_vacacional', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.empresa_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('empresa_id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci'
    )
    op.create_table('map_concepto_provision',
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('naturaleza', sa.CHAR(length=1), nullable=False),
    sa.Column('tipo', sa.CHAR(length=3), nullable=False),
    sa.Column('clave', sa.String(length=15), nullable=False),
    sa.Column('categoria', sa.Enum('AGUINALDO', 'VACACIONES', 'PRIMA_VACACIONAL', name='categoriaprovision'), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.empresa_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('empresa_id', 'naturaleza', 'tipo', 'clave'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci'
    )
    op.create_table('map_departamento',
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('departamento_texto', sa.String(length=100), nullable=False),
    sa.Column('centro_costo', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.empresa_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('empresa_id', 'departamento_texto'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('map_departamento')
    op.drop_table('map_concepto_provision')
    op.drop_table('configuracion_empresa')
    op.drop_table('tabla_vacaciones')
    op.drop_table('param_fiscal')
    op.drop_table('catalogo_percepcion_marca')
    # ### end Alembic commands ###
