"""add complemento pagos

Revision ID: 64d3d0de94e2
Revises: 93fce0fad1db
Create Date: 2026-08-05 18:07:36.280770

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64d3d0de94e2'
down_revision: Union[str, Sequence[str], None] = '93fce0fad1db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pago',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('comprobante_id', sa.Integer(), nullable=False),
    sa.Column('num_pago', sa.Integer(), nullable=False),
    sa.Column('fecha_pago', sa.DateTime(), nullable=True),
    sa.Column('forma_de_pago_p', sa.String(length=2), nullable=True),
    sa.Column('moneda_p', sa.CHAR(length=3), nullable=True),
    sa.Column('tipo_cambio_p', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('monto', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('num_operacion', sa.String(length=100), nullable=True),
    sa.Column('rfc_emisor_cta_ord', sa.String(length=13), nullable=True),
    sa.Column('cta_ordenante', sa.String(length=50), nullable=True),
    sa.Column('rfc_emisor_cta_ben', sa.String(length=13), nullable=True),
    sa.Column('cta_beneficiario', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['comprobante_id'], ['comprobantes.comprobante_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci'
    )
    op.create_index('idx_pago_comp', 'pago', ['comprobante_id'], unique=False)
    op.create_index('idx_pago_fecha', 'pago', ['fecha_pago'], unique=False)
    op.create_table('pago_totales',
    sa.Column('comprobante_id', sa.Integer(), nullable=False),
    sa.Column('total_traslados_base_iva16', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('total_traslados_impuesto_iva16', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('total_traslados_base_iva8', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('total_traslados_impuesto_iva8', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('total_traslados_base_iva0', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('total_traslados_impuesto_iva0', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('total_traslados_base_iva_exento', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('total_retenciones_iva', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('total_retenciones_isr', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('total_retenciones_ieps', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('monto_total_pagos', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.ForeignKeyConstraint(['comprobante_id'], ['comprobantes.comprobante_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('comprobante_id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci'
    )
    op.create_table('pago_docto',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pago_id', sa.Integer(), nullable=False),
    sa.Column('comprobante_id', sa.Integer(), nullable=False),
    sa.Column('id_documento', sa.CHAR(length=36), nullable=False),
    sa.Column('serie', sa.String(length=25), nullable=True),
    sa.Column('folio', sa.String(length=40), nullable=True),
    sa.Column('moneda_dr', sa.CHAR(length=3), nullable=True),
    sa.Column('equivalencia_dr', sa.Numeric(precision=18, scale=10), nullable=True),
    sa.Column('num_parcialidad', sa.Integer(), nullable=True),
    sa.Column('imp_saldo_ant', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('imp_pagado', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('imp_saldo_insoluto', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('objeto_imp_dr', sa.String(length=2), nullable=True),
    sa.ForeignKeyConstraint(['comprobante_id'], ['comprobantes.comprobante_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pago_id'], ['pago.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci'
    )
    op.create_index('idx_docto_comp', 'pago_docto', ['comprobante_id'], unique=False)
    op.create_index('idx_docto_documento', 'pago_docto', ['id_documento'], unique=False)
    op.create_table('pago_docto_impuesto',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pago_docto_id', sa.Integer(), nullable=False),
    sa.Column('comprobante_id', sa.Integer(), nullable=False),
    sa.Column('naturaleza', sa.CHAR(length=1), nullable=False),
    sa.Column('impuesto', sa.CHAR(length=3), nullable=False),
    sa.Column('tipo_factor', sa.String(length=10), nullable=True),
    sa.Column('tasa_o_cuota', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('base', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('importe', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.ForeignKeyConstraint(['comprobante_id'], ['comprobantes.comprobante_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pago_docto_id'], ['pago_docto.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci'
    )
    op.create_index('idx_pdi_comp', 'pago_docto_impuesto', ['comprobante_id', 'naturaleza', 'impuesto'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # `idx_pdi_comp`, `idx_docto_comp` e `idx_pago_comp` empiezan con la columna de una
    # FK hacia `comprobantes`: InnoDB los usa para satisfacer esa FK, así que un
    # `DROP INDEX` explícito falla con el error 1553. Se dejan fuera y el propio
    # `DROP TABLE` se lleva el índice (mismo ajuste que en la migración de la tarea 1).
    op.drop_table('pago_docto_impuesto')
    op.drop_index('idx_docto_documento', table_name='pago_docto')
    op.drop_table('pago_docto')
    op.drop_table('pago_totales')
    op.drop_index('idx_pago_fecha', table_name='pago')
    op.drop_table('pago')
    # ### end Alembic commands ###
