"""add configuracion_smtp

Revision ID: 707ce82c3acb
Revises: 6cd129c28602
Create Date: 2026-07-28 17:19:37.776541

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '707ce82c3acb'
down_revision: Union[str, Sequence[str], None] = '6cd129c28602'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('configuracion_smtp',
    sa.Column('config_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('host', sa.String(length=190), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('usuario', sa.String(length=190), nullable=False),
    sa.Column('password_cifrada', sa.LargeBinary(), nullable=False),
    sa.Column('dek_envuelta', sa.LargeBinary(), nullable=False),
    sa.Column('remitente', sa.String(length=190), nullable=False),
    sa.Column('tls', mysql.TINYINT(display_width=1), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('config_id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('configuracion_smtp')
    # ### end Alembic commands ###
