"""widen efirmas num_serie to 64 chars

Revision ID: 7baf380a4c55
Revises: a01acdd31dd9
Create Date: 2026-07-28 10:14:48.024193

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '7baf380a4c55'
down_revision: Union[str, Sequence[str], None] = 'a01acdd31dd9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('efirmas', 'num_serie',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=40),
               type_=sa.String(length=64),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('efirmas', 'num_serie',
               existing_type=sa.String(length=64),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=40),
               existing_nullable=False)
    # ### end Alembic commands ###
