"""add cfdi detalle conceptos impuestos relacionados

Revision ID: 93fce0fad1db
Revises: 15bebf60cc56
Create Date: 2026-08-05 17:46:39.256853

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93fce0fad1db'
down_revision: Union[str, Sequence[str], None] = '15bebf60cc56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cfdi_concepto',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('comprobante_id', sa.Integer(), nullable=False),
    sa.Column('num_linea', sa.Integer(), nullable=False),
    sa.Column('clave_prod_serv', sa.String(length=8), nullable=True),
    sa.Column('no_identificacion', sa.String(length=100), nullable=True),
    sa.Column('cantidad', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('clave_unidad', sa.String(length=3), nullable=True),
    sa.Column('unidad', sa.String(length=20), nullable=True),
    sa.Column('descripcion', sa.String(length=1000), nullable=True),
    sa.Column('valor_unitario', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('importe', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('descuento', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('objeto_imp', sa.String(length=2), nullable=True),
    sa.ForeignKeyConstraint(['comprobante_id'], ['comprobantes.comprobante_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('comprobante_id', 'num_linea', name='uq_concepto_linea'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci'
    )
    op.create_table('cfdi_relacionado',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('comprobante_id', sa.Integer(), nullable=False),
    sa.Column('tipo_relacion', sa.CHAR(length=2), nullable=False),
    sa.Column('uuid_relacionado', sa.CHAR(length=36), nullable=False),
    sa.ForeignKeyConstraint(['comprobante_id'], ['comprobantes.comprobante_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('comprobante_id', 'tipo_relacion', 'uuid_relacionado', name='uq_relacionado'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci'
    )
    op.create_table('comprobante_detalle',
    sa.Column('comprobante_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.String(length=5), nullable=True),
    sa.Column('serie', sa.String(length=25), nullable=True),
    sa.Column('fecha_timbrado', sa.DateTime(), nullable=True),
    sa.Column('forma_pago', sa.String(length=2), nullable=True),
    sa.Column('metodo_pago', sa.String(length=3), nullable=True),
    sa.Column('moneda', sa.CHAR(length=3), nullable=True),
    sa.Column('tipo_cambio', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('subtotal', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('descuento', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('lugar_expedicion', sa.String(length=5), nullable=True),
    sa.Column('exportacion', sa.String(length=2), nullable=True),
    sa.Column('regimen_emisor', sa.String(length=3), nullable=True),
    sa.Column('nombre_receptor', sa.String(length=300), nullable=True),
    sa.Column('domicilio_receptor', sa.String(length=5), nullable=True),
    sa.Column('regimen_receptor', sa.String(length=3), nullable=True),
    sa.Column('uso_cfdi', sa.String(length=4), nullable=True),
    sa.Column('no_certificado', sa.String(length=20), nullable=True),
    sa.Column('no_certificado_sat', sa.String(length=20), nullable=True),
    sa.Column('xml_hash', sa.CHAR(length=64), nullable=False),
    sa.Column('etl_version', sa.Integer(), nullable=False),
    sa.Column('normalizado_at', sa.DateTime(), nullable=True),
    sa.Column('error_normalizacion', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['comprobante_id'], ['comprobantes.comprobante_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('comprobante_id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci'
    )
    op.create_table('cfdi_concepto_impuesto',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('concepto_id', sa.Integer(), nullable=False),
    sa.Column('comprobante_id', sa.Integer(), nullable=False),
    sa.Column('naturaleza', sa.CHAR(length=1), nullable=False),
    sa.Column('impuesto', sa.CHAR(length=3), nullable=False),
    sa.Column('tipo_factor', sa.String(length=10), nullable=True),
    sa.Column('tasa_o_cuota', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('base', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('importe', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.ForeignKeyConstraint(['comprobante_id'], ['comprobantes.comprobante_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['concepto_id'], ['cfdi_concepto.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci'
    )
    op.create_index('idx_cci_comp_impuesto', 'cfdi_concepto_impuesto', ['comprobante_id', 'naturaleza', 'impuesto', 'tasa_o_cuota'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # NOTA: se ajustó a mano el orden autogenerado. MySQL/InnoDB usa
    # `idx_cci_comp_impuesto` para satisfacer el requisito de índice de la FK sobre
    # `comprobante_id`; intentar el DROP INDEX explícito antes de soltar la tabla
    # falla con error 1553 ("needed in a foreign key constraint"). Al soltar la tabla
    # completa, el índice se elimina junto con ella sin necesidad del DROP INDEX.
    op.drop_table('cfdi_concepto_impuesto')
    op.drop_table('comprobante_detalle')
    op.drop_table('cfdi_relacionado')
    op.drop_table('cfdi_concepto')
