"""initial

Revision ID: a01acdd31dd9
Revises: 
Create Date: 2026-07-27 17:11:28.309229

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'a01acdd31dd9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bitacora',
    sa.Column('bitacora_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('actor', sa.String(length=190), nullable=False),
    sa.Column('accion', sa.String(length=60), nullable=False),
    sa.Column('entidad', sa.String(length=120), nullable=False),
    sa.Column('detalle', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('bitacora_id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci'
    )
    op.create_index('idx_bit_entidad', 'bitacora', ['entidad'], unique=False)
    op.create_index('idx_bit_fecha', 'bitacora', ['created_at'], unique=False)
    op.create_table('configuracion',
    sa.Column('clave', sa.String(length=80), nullable=False),
    sa.Column('ejercicio_fiscal', sa.String(length=9), nullable=False),
    sa.Column('valor', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('clave', 'ejercicio_fiscal'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci'
    )
    op.create_table('empresas',
    sa.Column('empresa_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=190), nullable=False),
    sa.Column('rfc', sa.String(length=13), nullable=False),
    sa.Column('plantilla_nomenclatura', sa.String(length=190), nullable=False),
    sa.Column('genera_pdf_comprobante', mysql.TINYINT(display_width=1), nullable=False),
    sa.Column('activo', mysql.TINYINT(display_width=1), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.CheckConstraint('CHAR_LENGTH(rfc) BETWEEN 12 AND 13', name='chk_rfc'),
    sa.PrimaryKeyConstraint('empresa_id'),
    sa.UniqueConstraint('rfc'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci'
    )
    op.create_table('lista_69b',
    sa.Column('registro_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('rfc', sa.String(length=13), nullable=False),
    sa.Column('situacion', sa.Enum('presunto', 'definitivo', 'desvirtuado', 'sentencia_favorable', name='situacionefos'), nullable=False),
    sa.Column('fecha_publicacion', sa.Date(), nullable=True),
    sa.Column('version_lista', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('registro_id'),
    sa.UniqueConstraint('rfc', 'version_lista', name='uq_rfc_version'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci'
    )
    op.create_index('idx_69b_rfc', 'lista_69b', ['rfc'], unique=False)
    op.create_table('usuarios',
    sa.Column('usuario_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('firebase_uid', sa.String(length=128), nullable=False),
    sa.Column('correo', sa.String(length=190), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('rol_global', sa.Enum('admin', 'operador', 'consulta', name='rolglobal'), nullable=False),
    sa.Column('activo', mysql.TINYINT(display_width=1), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('usuario_id'),
    sa.UniqueConstraint('correo'),
    sa.UniqueConstraint('firebase_uid'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci'
    )
    op.create_table('efirmas',
    sa.Column('efirma_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('num_serie', sa.String(length=40), nullable=False),
    sa.Column('not_before', sa.DateTime(), nullable=False),
    sa.Column('not_after', sa.DateTime(), nullable=False),
    sa.Column('cer_pem', sa.LargeBinary(), nullable=False),
    sa.Column('key_cifrada', sa.LargeBinary(), nullable=False),
    sa.Column('password_cifrada', sa.LargeBinary(), nullable=False),
    sa.Column('dek_envuelta', sa.LargeBinary(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.empresa_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('efirma_id'),
    sa.UniqueConstraint('empresa_id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci'
    )
    op.create_table('eventos',
    sa.Column('evento_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('cancelacion_tardia', 'efos', 'efirma_por_vencer', 'error_descarga', 'resumen_sync', name='tipoevento'), nullable=False),
    sa.Column('detalle', sa.JSON(), nullable=False),
    sa.Column('hash_detalle', sa.CHAR(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.empresa_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('evento_id'),
    sa.UniqueConstraint('empresa_id', 'tipo', 'hash_detalle', name='uq_evento'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci'
    )
    op.create_table('jobs',
    sa.Column('job_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('emitido', 'recibido', name='tipojob'), nullable=False),
    sa.Column('solicitud', sa.Enum('CFDI', 'METADATA', name='solicitudtipo'), nullable=False),
    sa.Column('origen', sa.Enum('manual', 'sync', name='origenjob'), nullable=False),
    sa.Column('fecha_inicial', sa.Date(), nullable=False),
    sa.Column('fecha_final', sa.Date(), nullable=False),
    sa.Column('id_solicitud', sa.String(length=64), nullable=True),
    sa.Column('estado', sa.Enum('NUEVO', 'SOLICITADO', 'EN_PROCESO', 'TERMINADA', 'DESCARGADO', 'ERROR', name='estadojob'), nullable=False),
    sa.Column('intentos', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('paquetes', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('mensaje', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.CheckConstraint('fecha_final >= fecha_inicial', name='chk_rango'),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.empresa_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('job_id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci'
    )
    op.create_index('idx_jobs_empresa_estado', 'jobs', ['empresa_id', 'estado'], unique=False)
    op.create_index('idx_jobs_estado', 'jobs', ['estado'], unique=False)
    op.create_table('notificacion_destinos',
    sa.Column('destino_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('correo', sa.String(length=190), nullable=False),
    sa.Column('eventos_suscritos', mysql.SET('cancelacion_tardia', 'efos', 'efirma_por_vencer', 'error_descarga', 'resumen_sync'), nullable=False),
    sa.Column('activo', mysql.TINYINT(display_width=1), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.empresa_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('destino_id'),
    sa.UniqueConstraint('empresa_id', 'correo', name='uq_emp_correo'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci'
    )
    op.create_table('usuario_empresa',
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('rol', sa.Enum('operador', 'consulta', name='rolempresa'), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.empresa_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.usuario_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('usuario_id', 'empresa_id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci'
    )
    op.create_table('comprobantes',
    sa.Column('comprobante_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('uuid', sa.CHAR(length=36), nullable=False),
    sa.Column('folio', sa.String(length=40), nullable=True),
    sa.Column('rfc_emisor', sa.String(length=13), nullable=False),
    sa.Column('rfc_receptor', sa.String(length=13), nullable=False),
    sa.Column('razon_social_emisor', sa.String(length=254), nullable=True),
    sa.Column('total', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('fecha_emision', sa.DateTime(), nullable=True),
    sa.Column('tipo_comprobante', sa.CHAR(length=1), nullable=True),
    sa.Column('estatus', sa.Enum('vigente', 'cancelado', 'no_verificado', name='estatuscfdi'), nullable=False),
    sa.Column('estatus_verificado_at', sa.DateTime(), nullable=True),
    sa.Column('xml_path', sa.String(length=500), nullable=True),
    sa.Column('comprobante_path', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.empresa_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.job_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('comprobante_id'),
    sa.UniqueConstraint('empresa_id', 'uuid', name='uq_empresa_uuid'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci'
    )
    op.create_index('idx_comp_emisor', 'comprobantes', ['rfc_emisor'], unique=False)
    op.create_index('idx_comp_emp_estatus', 'comprobantes', ['empresa_id', 'estatus'], unique=False)
    op.create_index('idx_comp_emp_fecha', 'comprobantes', ['empresa_id', 'fecha_emision'], unique=False)
    op.create_index('idx_comp_emp_verif', 'comprobantes', ['empresa_id', 'estatus_verificado_at'], unique=False)
    op.create_table('notificacion_log',
    sa.Column('envio_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('evento_id', sa.Integer(), nullable=False),
    sa.Column('correo', sa.String(length=190), nullable=False),
    sa.Column('resultado', sa.Enum('enviado', 'fallido', name='resultadonotificacion'), nullable=False),
    sa.Column('mensaje', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['evento_id'], ['eventos.evento_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('envio_id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notificacion_log')
    op.drop_index('idx_comp_emp_verif', table_name='comprobantes')
    op.drop_index('idx_comp_emp_fecha', table_name='comprobantes')
    op.drop_index('idx_comp_emp_estatus', table_name='comprobantes')
    op.drop_index('idx_comp_emisor', table_name='comprobantes')
    op.drop_table('comprobantes')
    op.drop_table('usuario_empresa')
    op.drop_table('notificacion_destinos')
    op.drop_index('idx_jobs_estado', table_name='jobs')
    op.drop_index('idx_jobs_empresa_estado', table_name='jobs')
    op.drop_table('jobs')
    op.drop_table('eventos')
    op.drop_table('efirmas')
    op.drop_table('usuarios')
    op.drop_index('idx_69b_rfc', table_name='lista_69b')
    op.drop_table('lista_69b')
    op.drop_table('empresas')
    op.drop_table('configuracion')
    op.drop_index('idx_bit_fecha', table_name='bitacora')
    op.drop_index('idx_bit_entidad', table_name='bitacora')
    op.drop_table('bitacora')
    # ### end Alembic commands ###
