"""add confirmacion a catalogo_percepcion_marca

Extiende el invariante "un valor sin confirmar no calcula" a las marcas del §3.1:
`factor_exencion` alimenta el cálculo de exenciones igual que la UMA, los factores del
art. 93 de la LISR también cambian por reforma, y son 44 derivaciones hechas a mano —el
dato más propenso a error de la fase—, así que no pueden aplicarse solas mientras la UMA,
verificable contra un único boletín, sí exige un clic. Las columnas nacen nulas: las
marcas ya cargadas quedan como propuestas y hay que confirmarlas, que es el estado
correcto para un dato que nadie ha revisado.

Revision ID: aa2dd57754e8
Revises: 241164acbc81
Create Date: 2026-08-06 22:14:54.401263

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa2dd57754e8'
down_revision: Union[str, Sequence[str], None] = '241164acbc81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('catalogo_percepcion_marca', sa.Column('confirmado_por', sa.String(length=128), nullable=True))
    op.add_column('catalogo_percepcion_marca', sa.Column('confirmado_en', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('catalogo_percepcion_marca', 'confirmado_en')
    op.drop_column('catalogo_percepcion_marca', 'confirmado_por')
    # ### end Alembic commands ###
